
from variables.constants import SLICE_COMP_COMPOUNDIFIER_DICT


# R L' -->  RL',  D U' --> U'D, etc.   This block condenses slice comps into a single turn, with no space in the middle
def compoundify_comp_slice_turns(alg):
 
    # The addition of whitespace below is MISSING from the main branch, as of 6-1-2025. Some important algs failed to be generated by that branch, and I do not intend to fix it because, since every alg in that branch has an inverse (unlike with this one , with its leading X's but no trailing X's) all mistakes should be noticeable and findable. A good, useful alg with a T where there is no T', or vice versa, will stand out in the main branch. All the missed-opportunity algs, the algs that weren't generated, should  have a T (or an S, or an H), by the way.
    alg = alg + " "  # add trailing whitespace so that if an alg's final turn doesn't end with prime (') or 2, the dictionary still works
    
    for key, value in SLICE_COMP_COMPOUNDIFIER_DICT.items():
        alg = alg.replace(key, value)
    
    alg = alg.rstrip()   # remove trailing whitespace
    
    return alg
     





# NOT IN USE. But the coding is pretty cool. Found it on the interweb:
# def intersection_has_members(list1, list2):
#     temp = set(list2)
#     shared_members = [value for value in list1 if value in temp]
	
#     if shared_members:    # the if operator returns true in Python for any data structure that is non-empty
#         return True
#     else: 
#         return False 

