
# Note on TESTING: There are 3 lines of code that call testing methods.
# These methods simply add a few explanatory notes to the list of algs that will be written to file
# The methods are called TESTING_1, TESTING_2, TESTING_3.
# To add the notes:  Set is_test to TRUE in the file testing/is_test



def TESTING_1(ALL_ripple_rounds__final_algs, stic_master_dict):
     ALL_ripple_rounds__final_algs.extend(["\n\n\n\n\n\n", "original SS alg, or SS alg reversified, is:       %s\n"%(stic_master_dict["alg"]), "alg after slice insertion is:  %s\n"%(" ".join(stic_master_dict["turns"]))])
     # ideally, would change this verbiage to  "original SS alg, or SS alg reversified, is:  ". Then update the resultant testing suite results


     if stic_master_dict["is_reversified"]:
        ALL_ripple_rounds__final_algs.extend(["\n", "NOTE THAT THIS 'ORIGINAL ALG' IS A ***REVERSIFIED*** ALG !!!!! \nIT SHOULD BE THE SAME AS THE ORIGINAL ALG DIRECTLY ABOVE IT, BUT WITH 2 TURNS SWAPPED. \nSometimes there are no result algs here. That's okay. The code runs through the motions but the reversified alg faces \ntoo many exclusions to generate any results \n"])
     
     return(ALL_ripple_rounds__final_algs)




def TESTING_2(ALL_ripple_rounds__final_algs, trailing_YorZ_Xs_dual, trailing_YorZ_Xs):
    ALL_ripple_rounds__final_algs.extend(["\nDUAL list:  %s"%(trailing_YorZ_Xs_dual), "\nactive member of DUAL list:  %s"%(trailing_YorZ_Xs)  ])
    if trailing_YorZ_Xs[0] == "Y0" or trailing_YorZ_Xs[0] == "Z0":
        ALL_ripple_rounds__final_algs.extend(["", "Note that the YorZ component is a Y0 or Z0 !!!"])

    return ALL_ripple_rounds__final_algs




def TESTING_3(one_ripple_round_of__final_algs, indx, YorZ_added__shifting_turns):
    one_ripple_round_of__final_algs = ["", "", "YorZ_added__shifting_turns  is now:   " + " ".join(YorZ_added__shifting_turns), "\nThe indexes are going in reverse order; here are the algs for the current index, which is:  " + str(indx), "\nIF the alg's X-component is X0, the ripple round's base alg is added to the list.", "It is legit, but it has no wide comps so it isn't generated by CompXpansion.", "It will appear below, standing alone or with its merge_YU partner.", ""] + one_ripple_round_of__final_algs
    # ideally, would change this verbiage to  "YorZ_added__shifting_turns". Then update the resultant testing suite results


    return one_ripple_round_of__final_algs
